/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "operations.h"

bool_t
xdr_file_in (XDR *xdrs, file_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->fileName, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dir_in (XDR *xdrs, dir_in *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->dirName, 50,
		sizeof (char), (xdrproc_t) xdr_char))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_file_out (XDR *xdrs, file_out *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->chars))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->strings))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->rows))
		 return FALSE;
	return TRUE;
}
