/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "VotaFattoreX.h"

bool_t
xdr_Input (XDR *xdrs, Input *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidate_name, MAXSTRLEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->operation_name, MAXSTRLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Judge (XDR *xdrs, Judge *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->judge_name, MAXSTRLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Output (XDR *xdrs, Output *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->judges, N,
		sizeof (Judge), (xdrproc_t) xdr_Judge))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Candidate (XDR *xdrs, Candidate *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->candidate_name, MAXSTRLEN))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->judge_name, MAXSTRLEN))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->category))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->fileName, MAXSTRLEN))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->phase))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->vote))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_Table (XDR *xdrs, Table *objp)
{
	register int32_t *buf;

	int i;
	 if (!xdr_vector (xdrs, (char *)objp->candidate, N,
		sizeof (Candidate), (xdrproc_t) xdr_Candidate))
		 return FALSE;
	return TRUE;
}
