/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTAFATTOREX_H_RPCGEN
#define _VOTAFATTOREX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRLEN 255
#define N 15

struct Input {
	char *candidate_name;
	char *operation_name;
};
typedef struct Input Input;

struct Judge {
	char *judge_name;
};
typedef struct Judge Judge;

struct Output {
	Judge judges[N];
};
typedef struct Output Output;

struct Candidate {
	char *candidate_name;
	char *judge_name;
	char category;
	char *fileName;
	char phase;
	int score;
};
typedef struct Candidate Candidate;

struct Table {
	Candidate candidate[N];
};
typedef struct Table Table;

#define VOTAFATTORE 0x20000013
#define VOTAFATTOREVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define ranking 1
extern  Output * ranking_1(void *, CLIENT *);
extern  Output * ranking_1_svc(void *, struct svc_req *);
#define vote 2
extern  int * vote_1(Input *, CLIENT *);
extern  int * vote_1_svc(Input *, struct svc_req *);
extern int votafattore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define ranking 1
extern  Output * ranking_1();
extern  Output * ranking_1_svc();
#define vote 2
extern  int * vote_1();
extern  int * vote_1_svc();
extern int votafattore_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Judge (XDR *, Judge*);
extern  bool_t xdr_Output (XDR *, Output*);
extern  bool_t xdr_Candidate (XDR *, Candidate*);
extern  bool_t xdr_Table (XDR *, Table*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Judge ();
extern bool_t xdr_Output ();
extern bool_t xdr_Candidate ();
extern bool_t xdr_Table ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTAFATTOREX_H_RPCGEN */
