/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _VOTAFATTOREX_H_RPCGEN
#define _VOTAFATTOREX_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXSTRLEN 15
#define N 15

struct Input {
	char candidate_len[MAXSTRLEN];
	char operation_name[MAXSTRLEN];
};
typedef struct Input Input;

struct Judge {
	char judge_name[MAXSTRLEN];
};
typedef struct Judge Judge;

struct Output {
	Judge judges[N];
};
typedef struct Output Output;

#define VOTAFATTORE 0x20000013
#define VOTAFATTOREVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1(void *, CLIENT *);
extern  Output * classifica_giudici_1_svc(void *, struct svc_req *);
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1(Input *, CLIENT *);
extern  int * esprimi_voto_1_svc(Input *, struct svc_req *);
extern int votafattore_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CLASSIFICA_GIUDICI 1
extern  Output * classifica_giudici_1();
extern  Output * classifica_giudici_1_svc();
#define ESPRIMI_VOTO 2
extern  int * esprimi_voto_1();
extern  int * esprimi_voto_1_svc();
extern int votafattore_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_Input (XDR *, Input*);
extern  bool_t xdr_Judge (XDR *, Judge*);
extern  bool_t xdr_Output (XDR *, Output*);

#else /* K&R C */
extern bool_t xdr_Input ();
extern bool_t xdr_Judge ();
extern bool_t xdr_Output ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_VOTAFATTOREX_H_RPCGEN */
